# Generated by Django 4.1 on 2022-08-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colleges',
            old_name='eeservation',
            new_name='reservation',
        ),
    ]
