# Generated by Django 4.1 on 2022-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
