# Generated by Django 4.1 on 2022-08-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teachers_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
