# Generated by Django 4.1 on 2022-08-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teachers_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='reservation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colleges',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teachers'),
        ),
    ]
